= {lab_name}

Welcome to the *Troubleshooting Event-Driven Ansible in Ansible Automation Platform* lab. In this session, we will work with AAP 2.5, GitLab, and Zabbix Server. 
Labs 1 through 5 contain issues that need to be identified and resolved. Zabbix will monitor `node1`, and we will simulate an alert by stopping Apache. This alert will be sent to Event-Driven Ansible(Automation Decisions), which will use Ansible to resolve the detected issues. Several configuration changes will be required in the environment to achieve this.

=== Lab Access

The terminal window on your right is *already* logged into the *bastion* node as the `{ssh_user}`, if it is not please click "Terminals" in the top left of the left-side screen and two terminals will appear.

Your ssh key is located in the lab-user user's home folder in bastion node.

To copy your ssh key:

[source,bash]
----
[lab-user@bastion$ cd .ssh
[lab-user@bastion .ssh]$ scp config *.p* ec2-user@node1:.ssh/
----


== Lab Access Details

* If you are not already logged in to the bastion when you open the termails. Please log into them:

[subs=attributes+]
----
{ssh_command}
----

Bastion password `{ssh_password}`


== Ansible Automation Platform Web Console:
  * URL: https://{nginx_web_url}[window=_blank]
  * Username: `admin`
  * Password: `R3dh4t1!`

NOTE: To avoid being logged out, we recommed editing Settings -> Platform gateway -> Edit platform gateway settings and changing the Session cookie age to 7200.

== Access Gitlab running on server:
  * URL: https://server.{subdomain_base}[window=_blank]
  * Username: `root`
  * Password: `redhat..123`

== Access Zabbix running on server:
  * URL: http://server.{subdomain_base}/zabbix[window=_blank]
  * Username: `Admin`
  * Password: `zabbix`

NOTE: The Zabbix server is currently running on HTTP and not HTTPS. If your browser automatically switches the URL to HTTPS, you may need to manually change it back to HTTP to access the server.

== Access other instances from Bastion

* Log in to the Ansible Automation Platform Controller from bastion:

[subs=attributes+]
----
[lab-user@bastion ~]$ ssh controller
----

* Log in to the additional node from bastion:

[subs=attributes+]
----
[lab-user@bastion ~]$ ssh node1
----

* Log in to the additional server from bastion:

[subs=attributes+]
----
[lab-user@bastion ~]$ ssh server
----

== Documentation:
If you need the documentation link:

* https://ansible.readthedocs.io/projects/rulebook/en/stable/introduction.html[window=_blank]

* https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5[window=_blank]


=== Solution:

A step-by-step guided solution is provided at the end of each lab section. 
Before proceeding, take a moment to attempt the challenge on your own. 
The true value of this activity lies in your effort to troubleshoot independently. 
Once you have made an attempt, you can refer to the guided solutions to verify your approach or explore an alternate solution.
