= {lab_name}

Welcome to the Troubleshooting Event-Driven Ansible in AAP. 
In this lab we will work with AAP 2.5, Gitlab and Zabbix-Server.
The labs from 1.1 to 1.6 are all having problems running. We will need to find the problem and solve it.
Zabbix will monitor node1. We will force an alert, stopping Apache so that Zabbix can send the Alert to Event Driven.
The events of the problems found by Zabbix will be resolved by Ansible. For this to happen we will need to make several configurations in the environment.


== Lab structure

The challenges are in your Lab Instructions:
Your lab instructions are available at https://bastion.kv9wg.sandbox2018.opentlc.com:443/showroom/


== What each host has:
On node1 we have the folders to do the labs.

01-lab a 06-lab
Apache
zabbix-agent


Server:

Zabbix:  http://server.xxxx.sandbox2018.opentlc.com/zabbix
Username: Admin
Password: zabbix


Gitlab:  https://server.xxxx.sandbox2018.opentlc.com
Username: root
Password: redhat..123

Controller:
AAP 2.5: https://controller.kv9wg.sandbox2018.opentlc.com
Username: admin
Password: R3dh4t1!


=== Lab Access

The terminal window to your right is *already* logged into the lab environment as the `{ssh_user}` user via `ssh`. 

== Documentation:
If you need the documentation link:

* https://ansible.readthedocs.io/projects/rulebook/en/stable/introduction.html

* https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5


=== Solution:

In your lab instruction there is a section only with solutions to environmental problems.


