---
- name: Deploys VM based on cloud image
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Get VMs list
      community.libvirt.virt:
        command: list_vms
      register: existing_vms

    - name: Debug 
      ansible.builtin.debug: 
      var: existing_vms

